import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { GraphQLClient, gql } from "graphql-request";
import { useEffect, useState } from "react";

import BlogCard from "@/components/blog/BlogCard";
import { BlogCardTypes } from "@/components/blog/BlogCardTypes";
const inter = Inter({ subsets: ["latin"] });

const graphcms = new GraphQLClient(
  "https://api-ap-south-1.hygraph.com/v2/clefu7dgi02r601up2w9175vf/master"
);
const QUERY = gql`
  {
    posts {
      id
      title
      slug
      excerpt
      date
      coverImage {
        url
      }
      seo {
        keywords
      }
      tags
      author {
        id
        name
        picture {
          url
        }
      }
      content {
        html
      }
    }
  }
`;
export const getStaticProps = async () => {
  const { posts } = await graphcms.request(QUERY);
  posts.key = posts.id;
  return {
    props: {
      posts,
    },
    revalidate: 10,
  };
};
export default function Blog({ posts }: any) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {posts.map((item: BlogCardTypes, key: number) => {
          return (
            <div key={key}>
              <BlogCard {...item} />
            </div>
          );
        })}
      </main>
    </>
  );
}
